### PR TITLE
Add bundle exec to commands if Bundler is used

### PR DESCRIPTION
**Pull request by bostrom**
I added support for executing hookup through bundler. The original version assumed that hookup is found in PATH, but that might not be the case if hookup is installed through bundler. This PR prepends hookup commands with  ```bundle exec```.

### CODE REVIEW

**Comment by tpope** [comment]
This is a development tool that should definitely be possible to use without imposing changes on the project. The most I would entertain is a way to detect we are running as `bundle exec hookup install` and change the installed command if so.

**Comment by bostrom** [comment]
Yes, I thought of that too, but went with this quick solution. Let's see if I can come up with something proper later today.

**Comment by bostrom** [comment]
Alright, so I extracted the ```bundler exec``` addition to a wrapper that checks for the ```$BUNDLE_GEMFILE``` environment variable, which is set by bundler if a command is run through [bundle exec](http://bundler.io/man/bundle-exec.1.html). This DRYs up the ```install``` method and makes it all a bit more maintainable. 

How do you feel about this?

**Comment by tpope** [comment]
Sounds good, but lets leave it out of the README for now, as "if you use Bundler" implies the wrong thing. Squash it and I'll merge.

**Comment by bostrom** [comment]
Done. 

However, I find it a bit peculiar that a tool meant for Rails, which by default uses Bundler, which in turn does **not** by default put executables in PATH (```./bin``` in the project at best, but that's not guaranteed to be in PATH), and is used to automatically update the project's gems **using** Bundler, would instruct users to install the gem via the ```gem``` command instead of ```Gemfile``` **and** assume that the gem's executable is in PATH when installed. 

But maybe that's just me.

**Comment by tpope** [comment]
If I made, say, a text editor that specialized in Rails, I would instruct people to install it as a standalone tool, *not* add it to their Gemfile where it will install on every single disinterested collaborator's machine, not to mention production servers. Hookup isn't the same as a text editor but it does lean towards that end of the spectrum in that you can use it without the app or repository knowing at all. In fact I add hookup to my default Git template so that every single repository on my machine has it installed, without needing to taint a single code base.

Please squash to a single commit and force push.

**Comment by bostrom** [comment]
Ok, I see your point. In our case I would like to "force" hookup upon each developer in our team with the least possible amount of manual setup (which can be forgotten or messed up), but not necessarily having it in each project. This, for me, would be including it into the "development" section of the project's Gemfile and propagate that to all developers. This still requires the ```hookup install``` command to be manually issued by each team member, but that I can live with. 

Thanks for accepting the PR and for a great gem!

**Comment by tpope** [comment]
I think that is reasonable, but bear in mind it can burn you particularly in the short term, for example, when switching to a branch that doesn't have the gem declaration yet.

**Pull request merged**
